In [2]:
import numpy as np
lis=[1,2,3,4,5,6]
print(type(lis))
arr=np.array(lis)
print(type(arr))
print(arr)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3 4 5 6]


In [4]:
def fun():
    lis=[]
    for i in range(1,12,1):
        lis.append(i)
    print(lis)
fun()
        

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


In [5]:
arr=np.array(lis)
print(arr)

[1 2 3 4 5 6]


In [6]:
arr=np.eye(4,4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
arr=np.eye(4,4).reshape(8,2)
print(arr)

[[1. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [1. 0.]
 [0. 0.]
 [0. 1.]]


In [14]:
arr1=np.arange(1,13,1)
arr2=np.random.randint(0,100,12)
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2,int)


[ 15   4  96  72  46 102  55  47  43  50  75  52]
[-13   0 -90 -64 -36 -90 -41 -31 -25 -30 -53 -28]
[ 14   4 279 272 205 576 336 312 306 400 704 480]
[0.07142857 1.         0.03225806 0.05882353 0.12195122 0.0625
 0.14583333 0.20512821 0.26470588 0.25       0.171875   0.3       ] <class 'int'>


In [19]:
arr1=np.arange(1,100)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [20]:
for i in arr1:
    if i%3==0 and i%5==0:
        print(i,end=' ')

15 30 45 60 75 90 

In [1]:
import numpy as np
arr=np.random.randint(1,100,(5,5))
print(arr)

[[44 57 33 31 75]
 [68 63 53 78 29]
 [73 22 25 37 84]
 [30 82 67 17 80]
 [88 55 99 28 62]]


In [2]:
arr[:,::-1]

array([[75, 31, 33, 57, 44],
       [29, 78, 53, 63, 68],
       [84, 37, 25, 22, 73],
       [80, 17, 67, 82, 30],
       [62, 28, 99, 55, 88]])

# columns in the first matrix is the same as the number of rows in the second matrix

In [15]:
ar1=np.arange(12).reshape(4,3)
ar2=np.arange(9).reshape(3,3)
if ar1.shape[1]==ar2.shape[1]:
    print(ar1.dot(ar2))
else:
    print('not possible')


[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]
 [ 96 126 156]]


In [18]:
arr=np.random.randint(1,100,size=(6,6))
print(arr)
print(arr[3:6,3:6])

[[77 62 18 65 99 64]
 [45  8 25 14 19 82]
 [28 64 94 99  9 56]
 [77 70 58 66 10 97]
 [ 4 19 46 73 69 17]
 [24 21  9 96 22 97]]
[[66 10 97]
 [73 69 17]
 [96 22 97]]


## ## axis=0 equal to column
## axis =1 equal to row

In [26]:
arr=np.array([[2,4,3],[8,1,9]])
print(arr)
print('row wise ascending: \n',np.sort(arr,axis=1)) #row wise ascending
print('column wise ascending: \n',np.sort(arr,axis=0)) #column wise ascending
print('row wise descending:\n',-np.sort(-arr,axis=1))
print('column wise descending:\n',-np.sort(-arr,axis=0))

[[2 4 3]
 [8 1 9]]
row wise ascending: 
 [[2 3 4]
 [1 8 9]]
column wise ascending: 
 [[2 1 3]
 [8 4 9]]
row wise descending:
 [[4 3 2]
 [9 8 1]]
column wise descending:
 [[8 4 9]
 [2 1 3]]


In [31]:
dic={
    'name':'nishan',
    'age':24,
    'occupation':'researcher'
}
print(dic)
lis=list(dic.items())
print(lis)
li=np.array(lis)
print(li)

{'name': 'nishan', 'age': 24, 'occupation': 'researcher'}
[('name', 'nishan'), ('age', 24), ('occupation', 'researcher')]
[['name' 'nishan']
 ['age' '24']
 ['occupation' 'researcher']]


In [32]:
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [34]:
np.ones([3,3],dtype='int')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [35]:
np.zeros([3,3],dtype='int')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [38]:
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [39]:
arr1.max()

6

In [40]:
arr1.min()

1

In [41]:
ar=np.random.randint(1,100,size=(3,3))
ar

array([[52, 71, 67],
       [12, 50, 76],
       [20, 18, 51]])

In [42]:
ar=np.random.randint(1,100,7)
ar

array([40, 46, 18, 91, 17, 58,  3])

In [43]:
ar=np.diag([2,3,4,5])
ar

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

In [44]:
ar[2:,2:]

array([[4, 0],
       [0, 5]])

In [46]:
ar=np.random.randint(1,100,10)
ar

array([23, 61, 26, 96, 90, 49,  1, 23, 19, 10])

In [47]:
ar[::2]

array([23, 26, 90,  1, 19])

In [49]:
ar1=np.array([1,2,3,4])
ar2=np.array([5,6,7,8])
np.hstack((ar1,ar2))

array([1, 2, 3, 4, 5, 6, 7, 8])